apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cluster-project
data:
  DB_HOST: "postgres.cluster-project.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  # BACKEND_PORT peut aider selon ton app
  BACKEND_PORT: "3000"
